### ISSUE TITLE
RFC Bug/Feature Overview

### ISSUE THREAD

**Issue by daviddeutsch** [OwlCarousel2/OwlCarousel2#1309]
As noted in #1307, I need to get an overview on all the bugs and feature requests, so I'll be filing them in here and will try to figure out some form of categorization.

**Comment by daviddeutsch** [comment]
Alright, today I merged a bunch of PRs:

- [x] Avoid clipping when speed (and so duration) is 0 #988
- [x] Fixed when transform property is applied #1085
- [x] Fixing over-sensitive rightward swipe on touch devices #982
- [x] Fix transitionend support detection for Android 4.[1-3] #868
- [x] prevent half pixel blurry image. #1067

I also commented on a bunch of others to get additional feedback and cleaner PRs
