### ISSUE TITLE
Priorities going forward

### ISSUE THREAD

**Issue by daviddeutsch** [OwlCarousel2/OwlCarousel2#1538]
Hey everybody!

So @CracyCrazz and I met last Friday to talk through the current issues and decide a roadmap for the near future.

2017 Update: We've moved discussion over to the proper [ROADMAP TICKET](https://github.com/OwlCarousel2/OwlCarousel2/issues/1756).

# Roadmap
- [ ] 1. Gulp Pipeline

See #1330
- [ ] 2. Generating Documentation

This is part of #1330 - The documentation will need to move to a new version of assemble. While that is going on, it's probably a good idea to review the documentation in general to see whether we can clear up any frequently raised points.
- [ ] 3. Fix Clone Computation

This is still subject to analysis. The current state of the code is that generation of clones is very strange which creates a ton of fallout, from jumping carousels to a confusing API.

By strange I mean things like - The "prefixed" set of clones is never actually shown. Instead of using an offset, we basically copy markup that will never appear on any display, ever.
- [ ] 4. Cleanup "TODO" marks in the code

Especially the main .js file is peppered with TODO marks, often referencing outdated github issues. Both should be cleaned up.
- [ ] 5. Clean up Workers (Clones here, too)

The worker pipeline is at the heart of owlcarousel, so we need to be careful to not break something here, but ensuring that everything is working correctly (especially in relation to No.3, above) will likely fix a ton of bugs.
- [ ] 6. Remove CSS-Style Settings

This was a matter of heated debate. There are a few settings that I think end up being very confusing to people. I prefer software that is simple and I prefer to use CSS instead of Javascript for styling. There are a number of computations in owlcarousel that use fixed values (like the padding, from the settings) making the overall cognitive load to understand what's going on (for instance during computation of stage width etc.) needlessly complex.

A classic "bug" in that category is when people initialize a lot of carousels with the same command (copy and pasted, happens to include a padding) and see individual CSS rules overwritten by inline styles. Moving that to pure CSS should help make it easier to follow why a carousel ends up looking the way it does.
- [ ] 7. Fix CI Pipeline

CI hasn't been working for a while now. We really need to fix that - #1315 
# Finally

Tacking a big announcement at the end (in hopes that few people will read it :wink:):

There are actually significant issues with the name of the project and the domains attached to it. We have been trying, for a while now, to contact the owner of owlgraphic.com, @OwlFonk, to see whether we can clear that up and freshen up the version displayed there, but to no avail. That's a significant issue because there are a lot of old versions and documentation floating around creating lots and lots of problems - particularly in trying to maintain this repository. We occasionally manage to cut into the number of tickets on here, but as you've probably realized - we never get it to drop under 400 open tickets. A good number of people download an outdated version and have trouble migrating, or consult outdated documentation for a new version etc..

We talked quite a while about this and came to the conclusion that the most likely course of action for the future will be to fork the repository and relaunch the software under a new name. We have also discussed bigger overhauls like moving over to TypeScript, which seems another likely thing to happen.

**It's important to us that you understand:** Our primary focus right now is to make the v2.0 branch as dry and sound as possible. We're not looking for a quick exit - we want to get the project to a place where for 98% of users, it just works straight out of the box. Our main goal is to eliminate confusion and ensure a smooth experience for all users. We're confident that we have identified the major pain points that will allow us to do that and once we're finished, we will power down our efforts here to a certain degree.

We will use that "finishing" process to analyse what the future of owlcarousel could look like - whether under a new name or not.

As a final point - due to things like No.6 on our list, we might introduce a number of BC breaking changes, which would mean jumping to a new major version.

**Comment by leecollings** [comment]
Hello?

**Comment by hexcross** [comment]
ZzzzZzzz :(

**Comment by ccharlton** [comment]
+Sunset old (dupe) website

**Comment by daviddeutsch** [comment]
We've moved discussion over to the proper [ROADMAP TICKET](https://github.com/OwlCarousel2/OwlCarousel2/issues/1756)
